### ISSUE TITLE
"Math domain error" problem

### ISSUE THREAD

**Issue by dcm9123** [PatWalters/metk#2]
Hi! I am trying to run the metk.py in my computer using the file as an example, however I am getting an error after I type this:

`python metk.py --in /Users/Danniel/metk/fep_kcal.csv --prefix test_pw`

As you can see, I am omitting the [--units uM] and [--example], as I want to leave the default values, and the error I am getting is the following: 

```
Traceback (most recent call last):
  File "metk.py", line 28, in <module>
    df = ki_to_kcal_df(df)
  File "/Users/Danniel/metk/modelevaltoolkit/metk_util.py", line 126, in ki_to_kcal_df
    new_df['Pred'] = [ki_to_kcal(x, units) for x in df['Pred']]
  File "/Users/Danniel/metk/modelevaltoolkit/metk_util.py", line 55, in ki_to_kcal
    return math.log(ic50 * multiplier) * 0.5961
ValueError: math domain error

```

Thanks in advance!

**Comment by dcm9123** [comment]
I believed it's because you have negative values in the document, and it looks like the values you have belong to delta G, is that correct?

**Comment by PatWalters** [comment]
Sorry, this was a stupid bug on my part.  The metk.py script expects the input to be in kcal/mol.  The call to ki_to_kcal should have been commented out.  This has been fixed.  My apologies for any hassles.

**Comment by dcm9123** [comment]
Thank you! That is very helpful! So, just to make sure... The code only takes files which input is kcal/mol? So, whenever I call the program in the terminal, should I avoid the [--units uM]? if I do so, will it consider kcal/mol by default?

Thanks again!

**Comment by PatWalters** [comment]
Input is always in kcal/mol.   The --units flag only affects the second plot in the pdf output.   You can change whether that plot is displayed with uM or nM as the units.  I'll make this more clear in the README file.

**Comment by dcm9123** [comment]
I see, thank you for the clarification!
